export default [
  {
    id: 1,
    spots: 142,
    image: 'images/image1.png',
    title: 'text',
    rating: '5.0',
    location: 'USA',
    reviews: '6',
    price: '139',
    spots: 0,
  },
  {
    id: 2,
    image: 'images/image1.png',
    title: 'text',
    rating: '5.0',
    location: 'Online',
    reviews: '6',
    price: '139',
    spots: 142,
  },
  {
    id: 3,
    image: 'images/image1.png',
    title: 'text',
    rating: '5.0',
    location: 'USA',
    reviews: '6',
    price: '139',
    spots: 142,
  },
  {
    id: 4,
    image: 'images/image1.png',
    title: 'text',
    rating: '5.0',
    location: 'USA',
    reviews: '6',
    price: '139',
    spots: 142,
  },
]
